# Generated by Django 6.1 on 2026-09-17 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_product_quantity_per_unit_product_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='category',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='product',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_by',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.unit'),
        ),
    ]
