# Generated by Django 6.1 on 2026-09-17 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_brand_created_by_alter_category_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
