# Generated by Django 6.1 on 2026-10-01 01:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_wholesale_price_product_wholesale_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='wholesale_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_quantity',
        ),
        migrations.RemoveField(
            model_name='product',
            name='wholesale_unit_name',
        ),
    ]
