# Generated by Django 6.1 on 2026-10-01 07:39

import uuid
from decimal import Decimal

from django.db import migrations, models


def create_base_product_units(apps, schema_editor):
    """Create ProductUnit records for existing products using their current unit as base unit."""
    Product = apps.get_model("products", "Product")
    Unit = apps.get_model("products", "Unit")
    ProductUnit = apps.get_model("products", "ProductUnit")
    User = apps.get_model("accounts", "User")

    # Get the first user as default creator
    default_user = User.objects.first()

    for product in Product.objects.all():
        # Create the base unit configuration (conversion_factor = 1)
        ProductUnit.objects.create(
            product=product,
            unit=product.unit,
            conversion_factor=Decimal("1.0000"),
            allow_decimal=False,
            buying_price=product.buying_price,
            selling_price=product.selling_price,
            is_active=True,
            created_by=default_user,
        )


def migrate_unit_quantity_to_product_units(apps, schema_editor):
    """Migrate existing Unit.quantity values to ProductUnit conversion factors where applicable."""
    Product = apps.get_model("products", "Product")
    Unit = apps.get_model("products", "Unit")
    ProductUnit = apps.get_model("products", "ProductUnit")

    # For units that have quantity > 1, check if any product uses them
    # as a non-base unit. This is a best-effort migration.
    pass  # Complex migration - may need manual review


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0010_remove_product_wholesale_price_and_more"),
        ("accounts", "0004_user_role_default"),
    ]

    operations = [
        # Step 1: Add new fields to Unit model
        migrations.AddField(
            model_name="unit",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        # Step 2: Add ProductUnit model
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("uuid", models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ("created_by", models.ForeignKey(on_delete=models.PROTECT, to="accounts.user")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("conversion_factor", models.DecimalField(decimal_places=4, max_digits=10)),
                ("allow_decimal", models.BooleanField(default=False)),
                ("buying_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("selling_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("is_active", models.BooleanField(default=True)),
                ("product", models.ForeignKey(on_delete=models.CASCADE, related_name="product_units", to="products.product")),
                ("unit", models.ForeignKey(on_delete=models.PROTECT, related_name="product_units", to="products.unit")),
            ],
            options={
                "ordering": ["conversion_factor"],
            },
        ),
        migrations.AddConstraint(
            model_name="productunit",
            constraint=models.UniqueConstraint(fields=("product", "unit"), name="unique_product_unit"),
        ),
        # Step 3: Add base_unit field to Product (nullable initially)
        migrations.AddField(
            model_name="product",
            name="base_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=models.PROTECT,
                related_name="base_products",
                to="products.unit",
            ),
        ),
        # Step 4: Migrate data - set base_unit to current unit
        migrations.RunSQL(
            sql="UPDATE products_product SET base_unit_id = unit_id;",
            reverse_sql="UPDATE products_product SET unit_id = base_unit_id;",
        ),
        # Step 5: Make base_unit non-nullable
        migrations.AlterField(
            model_name="product",
            name="base_unit",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="base_products",
                to="products.unit",
            ),
        ),
        # Step 6: Create ProductUnit records for existing products
        migrations.RunPython(create_base_product_units, migrations.RunPython.noop),
        # Step 7: Remove old unit field from Product
        migrations.RemoveField(
            model_name="product",
            name="unit",
        ),
        # Step 8: Remove quantity field from Unit
        migrations.RemoveField(
            model_name="unit",
            name="quantity",
        ),
    ]