# Generated by Django 6.1 on 2026-10-01 11:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_alter_unit_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productunit',
            name='allow_decimal',
        ),
        migrations.AlterField(
            model_name='productunit',
            name='conversion_factor',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
