# Generated by Django 6.1 on 2026-09-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='saleitem',
            name='created_by',
        ),
    ]
