# Generated by Django 6.1 on 2026-10-01 00:34

from django.db import migrations, models


def backfill_sale_unit_uuids(apps, schema_editor):
    SaleItem = apps.get_model("sales", "SaleItem")
    Unit = apps.get_model("products", "Unit")
    Product = apps.get_model("products", "Product")

    # Product.unit was replaced by Product.base_unit in the unit-conversion
    # refactor. Skip this legacy backfill when the relation no longer exists;
    # the refactor migration resolves units from the real data instead.
    product_field_names = {field.name for field in Product._meta.get_fields()}
    if "unit" not in product_field_names:
        return

    units_by_name = {unit.name: str(unit.uuid) for unit in Unit.objects.all()}
    base_units = {
        product.pk: str(product.unit.uuid)
        for product in Product.objects.select_related("unit")
    }
    for item in SaleItem.objects.filter(unit_uuid="").iterator():
        item.unit_uuid = units_by_name.get(item.unit_name, base_units[item.product_id])
        item.save(update_fields=["unit_uuid"])


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_saleitem_unit_name_saleitem_unit_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleitem",
            name="unit_uuid",
            field=models.CharField(blank=True, default="", max_length=36),
        ),
        migrations.RunPython(backfill_sale_unit_uuids, migrations.RunPython.noop),
    ]
