# Generated by Django 6.1 on 2026-10-01 07:43

from django.db import migrations, models


def migrate_sale_items(apps, schema_editor):
    """Migrate existing SaleItem data to new structure."""
    SaleItem = apps.get_model("sales", "SaleItem")
    ProductUnit = apps.get_model("products", "ProductUnit")
    Unit = apps.get_model("products", "Unit")
    User = apps.get_model("accounts", "User")

    default_user = User.objects.first()

    for item in SaleItem.objects.all():
        # Find the Unit by UUID.
        # Old records may have an empty or invalid unit_uuid.
        if item.unit_uuid:
            try:
                unit = Unit.objects.get(uuid=item.unit_uuid)
            except (Unit.DoesNotExist, ValueError):
                unit = item.product.base_unit
        else:
            unit = item.product.base_unit

        # Find or create the ProductUnit for this product and unit
        product_unit, created = ProductUnit.objects.get_or_create(
            product=item.product,
            unit=unit,
            defaults={
                "conversion_factor": item.unit_quantity or 1,
                "allow_decimal": False,
                "buying_price": item.unit_price,
                "selling_price": item.unit_price,
                "is_active": True,
                "created_by": default_user,
            },
        )

        if not created:
            # Update with the conversion factor used historically
            product_unit.conversion_factor = item.unit_quantity or 1
            product_unit.selling_price = item.unit_price
            product_unit.save()

        # Determine sale_type from unit_type
        sale_type = "wholesale" if item.unit_type == "wholesale" else "retail"

        # Update the item with new fields
        item.product_unit = product_unit
        item.sale_type = sale_type
        item.conversion_factor_used = product_unit.conversion_factor
        item.base_quantity = (item.quantity or 0) * (
            product_unit.conversion_factor or 1
        )
        item.unit_name = item.unit_name or product_unit.unit.name
        item.unit_abbreviation = product_unit.unit.abbreviation or ""
        item.product_name = item.product.name
        item.save()


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('sales', '0009_saleitem_unit_uuid'),
        ('products', '0011_auto_20261001_1039'),
        ('accounts', '0004_user_role_default'),
    ]

    operations = [
        # Step 1: Add product_unit field (nullable initially)
        migrations.AddField(
            model_name="saleitem",
            name="product_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=models.PROTECT,
                related_name="sale_items",
                to="products.productunit",
            ),
        ),
        # Step 2: Add sale_type field
        migrations.AddField(
            model_name="saleitem",
            name="sale_type",
            field=models.CharField(
                choices=[("wholesale", "Wholesale"), ("retail", "Retail")],
                default="retail",
                max_length=10,
            ),
        ),
        # Step 3: Add new fields for conversion tracking
        migrations.AddField(
            model_name="saleitem",
            name="conversion_factor_used",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="base_quantity",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=12
            ),
        ),
        # Step 4: Add snapshot fields
        migrations.AddField(
            model_name="saleitem",
            name="unit_abbreviation",
            field=models.CharField(blank=True, max_length=10, default=""),
        ),
        migrations.AddField(
            model_name="saleitem",
            name="product_name",
            field=models.CharField(max_length=150, default=""),
        ),
        # Step 5: Migrate data
        migrations.RunPython(migrate_sale_items, migrations.RunPython.noop),
        # Step 6: Make product_unit non-nullable
        migrations.AlterField(
            model_name="saleitem",
            name="product_unit",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="sale_items",
                to="products.productunit",
            ),
        ),
        # Step 7: Change quantity from PositiveIntegerField to DecimalField
        migrations.AlterField(
            model_name="saleitem",
            name="quantity",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        # Step 8: Remove old fields
        migrations.RemoveField(
            model_name="saleitem",
            name="unit_type",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="unit_uuid",
        ),
        migrations.RemoveField(
            model_name="saleitem",
            name="unit_quantity",
        ),
    ]
