# Generated by Django 6.1 on 2026-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_active',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('salesperson', 'Salesperson'), ('storekeeper', 'Storekeeper'), ('accountant', 'Accountant')], max_length=20),
        ),
    ]
