# Generated by Django 6.1 on 2026-09-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='created_by',
        ),
    ]
