# Generated by Django 6.1 on 2026-09-17 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0006_alter_stock_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('Initial Stock', 'Initial'), ('Purchases', 'Purchases'), ('Sales', 'Sales'), ('Return', 'Return'), ('Damages', 'Damages')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
