# Generated by Django 6.1 on 2026-09-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0007_alter_stock_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('Initial Stock', 'Initial'), ('Purchases', 'Purchases'), ('Sales', 'Sales'), ('Purchase Adjustment', 'Purchase Adjustment'), ('Sales Adjustment', 'Sales Adjustment'), ('Return', 'Return'), ('Damages', 'Damages'), ('Cancellation', 'Cancel')], max_length=20),
        ),
    ]
