# Generated by Django 6.1 on 2026-09-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0008_alter_stockmovement_movement_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('Initial Stock', 'Initial'), ('Purchases', 'Purchases'), ('Sales', 'Sales'), ('Purchase Adjustment', 'Purchase Adjustment'), ('Sales Adjustment', 'Sales Adjustment'), ('Return', 'Return'), ('Damages', 'Damages'), ('Cancellation', 'Cancel'), ('Stocktake Surplus', 'Stocktake Surplus'), ('Stocktake Loss', 'Stocktake Loss')], max_length=20),
        ),
    ]
