# Generated by Django 6.1 on 2026-10-01 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0010_shorten_movement_references'),
        ('products', '0011_auto_20261001_1039'),
    ]

    operations = [
        # Step 1: Change Stock.quantity from PositiveIntegerField to DecimalField
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        # Step 2: Add new fields to StockMovement for transaction unit tracking
        migrations.AddField(
            model_name="stockmovement",
            name="transaction_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="stock_movements",
                to="products.unit",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="transaction_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="transaction_unit_name",
            field=models.CharField(blank=True, max_length=50, default=""),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="conversion_factor_used",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="base_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=models.PROTECT,
                related_name="base_stock_movements",
                to="products.unit",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="base_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=4, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="base_unit_name",
            field=models.CharField(blank=True, max_length=50, default=""),
        ),
    ]