# Generated by Django 6.1 on 2026-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0011_auto_20261001_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='base_unit_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('Initial Stock', 'Initial'), ('Purchases', 'Purchases'), ('Sales', 'Sales'), ('Purchase Adjustment', 'Purchase Adjustment'), ('Sales Adjustment', 'Sales Adjustment'), ('Return', 'Return'), ('Damages', 'Damages'), ('Cancellation', 'Cancel'), ('Stocktake Surplus', 'Stocktake Surplus'), ('Stocktake Loss', 'Stocktake Loss')], max_length=30),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='transaction_unit_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
