# Generated by Django 6.1 on 2026-10-02 11:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('email_attempted', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('event', models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('token_refresh', 'Token refresh'), ('logout', 'Logout'), ('access_denied', 'Access denied'), ('password_changed', 'Password changed'), ('password_reset_requested', 'Password reset requested')], db_index=True, max_length=30)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('ip_version', models.PositiveSmallIntegerField(choices=[(4, 'IPv4'), (6, 'IPv6')])),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('device_type', models.CharField(blank=True, max_length=20)),
                ('os_name', models.CharField(blank=True, max_length=80)),
                ('browser_name', models.CharField(blank=True, max_length=80)),
                ('country', models.CharField(blank=True, db_index=True, max_length=80)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('region', models.CharField(blank=True, max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('is_first_login', models.BooleanField(default=False)),
                ('is_new_device', models.BooleanField(default=False)),
                ('previous_ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('previous_login_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts_before', models.PositiveIntegerField(default=0)),
                ('previous_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('entry_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='access_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'access log',
                'verbose_name_plural': 'access logs',
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
