# Generated by Django 6.1 on 2026-09-30 23:23

from django.db import migrations, models


def populate_purchase_item_units(apps, schema_editor):
    PurchaseItem = apps.get_model("purchases", "PurchaseItem")

    # Product.unit was replaced by Product.base_unit in the unit-conversion
    # refactor. When this historical backfill replays on a database whose
    # products table is already migrated, the legacy relation is gone and the
    # later refactor migration rebuilds these values from the real data.
    field_names = {field.name for field in PurchaseItem._meta.get_fields()}
    if "product" not in field_names:
        return

    product_field_names = {
        field.name
        for field in apps.get_model("products", "Product")._meta.get_fields()
    }
    if "unit" not in product_field_names:
        return

    for item in (
        PurchaseItem.objects.filter(unit_name="")
        .select_related("product__unit")
        .iterator()
    ):
        item.unit_name = item.product.unit.name
        item.save(update_fields=["unit_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("purchases", "0007_alter_purchase_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="unit_name",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="unit_quantity",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="unit_type",
            field=models.CharField(
                choices=[("base", "Base unit"), ("wholesale", "Wholesale unit")],
                default="base",
                max_length=12,
            ),
        ),
        migrations.RunPython(populate_purchase_item_units, migrations.RunPython.noop),
    ]
