# Generated by Django 6.1 on 2026-10-01 07:42

from django.db import migrations, models


def migrate_purchase_items(apps, schema_editor):
    """Migrate existing PurchaseItem data to new structure."""
    PurchaseItem = apps.get_model("purchases", "PurchaseItem")
    ProductUnit = apps.get_model("products", "ProductUnit")
    Unit = apps.get_model("products", "Unit")
    User = apps.get_model("accounts", "User")

    default_user = User.objects.first()

    for item in PurchaseItem.objects.all():
        # Find the Unit by UUID
        try:
            unit = Unit.objects.get(uuid=item.unit_uuid)
        except Unit.DoesNotExist:
            # Fallback to product's base unit
            unit = item.product.base_unit

        # Find or create the ProductUnit for this product and unit
        product_unit, created = ProductUnit.objects.get_or_create(
            product=item.product,
            unit=unit,
            defaults={
                "conversion_factor": item.unit_quantity or 1,
                "allow_decimal": False,
                "buying_price": item.unit_cost,
                "selling_price": item.unit_cost,
                "is_active": True,
                "created_by": default_user,
            },
        )
        if not created:
            # Update with the conversion factor used historically
            product_unit.conversion_factor = item.unit_quantity or 1
            product_unit.buying_price = item.unit_cost
            product_unit.save()

        # Update the item with new fields
        item.product_unit = product_unit
        item.conversion_factor_used = product_unit.conversion_factor
        item.base_quantity = (item.quantity or 0) * (product_unit.conversion_factor or 1)
        item.unit_name = item.unit_name or product_unit.unit.name
        item.unit_abbreviation = product_unit.unit.abbreviation or ""
        item.product_name = item.product.name
        item.save()


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0009_purchaseitem_unit_uuid'),
        ('products', '0011_auto_20261001_1039'),
        ('accounts', '0004_user_role_default'),
    ]

    operations = [
        # Step 1: Add product_unit field (nullable initially)
        migrations.AddField(
            model_name="purchaseitem",
            name="product_unit",
            field=models.ForeignKey(
                null=True,
                on_delete=models.PROTECT,
                related_name="purchase_items",
                to="products.productunit",
            ),
        ),
        # Step 2: Add new fields for conversion tracking
        migrations.AddField(
            model_name="purchaseitem",
            name="conversion_factor_used",
            field=models.DecimalField(
                decimal_places=4, default=1, max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="base_quantity",
            field=models.DecimalField(
                decimal_places=4, default=0, max_digits=12
            ),
        ),
        # Step 3: Add snapshot fields
        migrations.AddField(
            model_name="purchaseitem",
            name="unit_abbreviation",
            field=models.CharField(blank=True, max_length=10, default=""),
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="product_name",
            field=models.CharField(max_length=150, default=""),
        ),
        # Step 4: Migrate data
        migrations.RunPython(migrate_purchase_items, migrations.RunPython.noop),
        # Step 5: Make product_unit non-nullable
        migrations.AlterField(
            model_name="purchaseitem",
            name="product_unit",
            field=models.ForeignKey(
                on_delete=models.PROTECT,
                related_name="purchase_items",
                to="products.productunit",
            ),
        ),
        # Step 6: Change quantity from PositiveIntegerField to DecimalField
        migrations.AlterField(
            model_name="purchaseitem",
            name="quantity",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        # Step 7: Remove old fields
        migrations.RemoveField(
            model_name="purchaseitem",
            name="unit_type",
        ),
        migrations.RemoveField(
            model_name="purchaseitem",
            name="unit_uuid",
        ),
        migrations.RemoveField(
            model_name="purchaseitem",
            name="unit_quantity",
        ),
    ]