# Generated by Django 6.1 on 2026-10-01 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0010_auto_20261001_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='base_quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='conversion_factor_used',
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='product_name',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='unit_name',
            field=models.CharField(max_length=50),
        ),
    ]
