# Generated by Django 6.1 on 2026-10-01 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0011_alter_purchaseitem_base_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseitem',
            name='base_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='conversion_factor_used',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='purchaseitem',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
